In [ ]:
import infection as inf

In [1]:
import numpy as np

In [2]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
class Mundo:
    
    def __init__(self, n_columnas, n_filas):

        self.numero_columnas = n_columnas
        self.numero_filas = n_filas

        self.mapa = np.zeros((n_filas, n_columnas), dtype=int)

    def ocupacion_inicial(self, ocupacion):

        numero_celdas_ocupadas = ocupacion * self.numero_columnas * self.numero_filas
        numero_celdas_ocupadas = int(numero_celdas_ocupadas)

        contador  = 0

        while contador<numero_celdas_ocupadas:

            ii = np.random.randint(0,self.numero_filas)
            jj = np.random.randint(0,self.numero_columnas)

            if (self.mapa[ii,jj]==0):
                self.mapa[ii,jj]=1
                contador = contador + 1

In [41]:
mundo_1 = Mundo(100, 200)

In [42]:
mundo_1.mapa

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(200, 100))

In [43]:
mundo_1.ocupacion_inicial(0.30)

In [44]:
mundo_1.mapa

array([[0, 1, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 1, 1, 0],
       [0, 0, 1, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 1, 1, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]], shape=(200, 100))

In [26]:
int(0.324)

0